[project]
name = "example-setup-uv"
version = "0.1.0"
description = "Example project that runs uv inside a docker container"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]==0.115.5"
]